version: '3.8'
services:
  server0:
    build:
      context: ../
      dockerfile: ./IntegrationTest/Dockerfile
    networks:
      smr-network:
        ipv4_address: 192.168.10.2
  server1:
    build:
      context: ../
      dockerfile: ./IntegrationTest/Dockerfile
    networks:
      smr-network:
        ipv4_address: 192.168.10.3
  server2:
    build:
      context: ../
      dockerfile: ./IntegrationTest/Dockerfile
    networks:
      smr-network:
        ipv4_address: 192.168.10.4
  server3:
    build:
      context: ../
      dockerfile: ./IntegrationTest/Dockerfile
    networks:
      smr-network:
        ipv4_address: 192.168.10.5
  client:
    build:
      context: ../
      dockerfile: ./IntegrationTest/Dockerfile
    networks:
      smr-network:
        ipv4_address: 192.168.10.6
  tester:
    build:
      context: .
      dockerfile: ./tester/Dockerfile
    ports:
      - "2222:2222"
    networks:
      smr-network:
        ipv4_address: 192.168.10.7

networks:
  smr-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24


